// <auto-generated />
namespace DeusCloud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Newunsirancesteal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newunsirancesteal));
        
        string IMigrationMetadata.Id
        {
            get { return "201707141436293_New-unsirance-steal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
